import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NextUIProvider } from "@nextui-org/react";
import { Footer } from "@/UI/Footer/Footer";
import { Navbar } from "@/UI/Navbar/Navbar";
import { SessionProvider } from "next-auth/react";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <Navbar />
          <main className="min-h-screen text-balance">
            <NextUIProvider>{children}</NextUIProvider>
          </main>
          {/* <WebVitals /> */}
          <Footer />
        </SessionProvider>
      </body>
    </html>
  );
}
